baseURL = 'https://workshops.mydevopsteam.io'
languageCode = 'en-us'
title = 'MyDevOpsTeam WorkShops'
theme = 'hugo-theme-learn'

[params]
  editURL = "https://github.com/MyDevOpsTeam-io/workshop-gh-src/"
  # Author of the site, will be used in meta information
  author = "mydevopsteam.io"
  # Description of the site, will be used in meta information
  description = "mydevopsteam.io workshop"
  titleSeparator = "-"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"
weight = 30
